name       : phoronix-test-suite
version    : 10.4.0
release    : 26
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/archive/refs/tags/v10.4.0.tar.gz : 4feda834008c9844bbe675a6ce9b88a44d36965bc2d0a9d62c1407ba5b084935
license    : GPL-3.0-or-later
component  : programming
homepage   : https://www.phoronix-test-suite.com/
summary    : Comprehensive testing and benchmarking platform
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0001-Re-enable-systemd-inhibit.patch
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
install    : |
    DESTDIR="$installdir" bash ./install-sh %PREFIX%
