name       : phoronix-test-suite
version    : 7.0.0
release    : 3
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v7.0.0.tar.gz : ed266e909e3eb05b6480b00b0025c4d616fe8952d4df5f69eeffe593d7b7e453
license    : GPL-3.0
summary    : Comprehensive testing and benchmarking platform
component  : programming
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
install    : |
    DESTDIR=${installdir} bash ./install-sh /usr
