name       : phoronix-test-suite
version    : 8.0.1
release    : 8
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v8.0.1.tar.gz : 8bfe972c601884f2bbbf4d5069c7691637e8a30af55d2a9597dbe53911b49081
license    : GPL-3.0-or-later
component  : programming
summary    : Comprehensive testing and benchmarking platform
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
install    : |
    DESTDIR=${installdir} bash ./install-sh /usr
