name       : phoronix-test-suite
version    : 8.4.1
release    : 11
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v8.4.1.tar.gz : 29e2221ce0db9d11f98cbdab3f45c60e87868b366b00ad698e1a45fee8a96764
license    : GPL-3.0-or-later
component  : programming
summary    : Comprehensive testing and benchmarking platform
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
install    : |
    DESTDIR=${installdir} bash ./install-sh %PREFIX%
