name       : phoronix-test-suite
version    : 9.0.1
release    : 16
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v9.0.1.tar.gz : 66f57eeb12241966cb7ad6594981bfd6ccdb28c4a14325271bec50c810d041db
license    : GPL-3.0-or-later
component  : programming
summary    : Comprehensive testing and benchmarking platform
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
install    : |
    DESTDIR=${installdir} bash ./install-sh %PREFIX%
