name       : phoronix-test-suite
version    : 6.6.1
release    : 1
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v6.6.1.tar.gz : 853d853d804aadc41a9faea33c294f3c817b3640658f3659fce72cb0d498042a
license    : GPL-3.0
summary    : Comprehensive testing and benchmarking platform
component  : programming
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0001-pts-core-Update-Solus-external-dependency-handling.patch
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
    %patch -p1 < $pkgfiles/0003-pts-core-Update-latest-Solus-dependency-libs.patch
install    : |
    DESTDIR=${installdir} bash ./install-sh /usr
