name       : phoronix-test-suite
version    : 10.2.0
release    : 24
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/releases/download/v10.2.0/phoronix-test-suite-10.2.0.tar.gz : 7a828781b4b2384930ce48b9c16b9994e0266658f138c5dcced03f83c4edbad4
license    : GPL-3.0-or-later
component  : programming
homepage   : https://www.phoronix-test-suite.com/
summary    : Comprehensive testing and benchmarking platform
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0001-Re-enable-systemd-inhibit.patch
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
install    : |
    DESTDIR="$installdir" bash ./install-sh %PREFIX%
