name       : phoronix-test-suite
version    : 8.8.0
release    : 14
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v8.8.0.tar.gz : 06ff8602e0b8035e1b6424656002ffa4b61844d1f4250d6801a5d2d495755709
license    : GPL-3.0-or-later
component  : programming
summary    : Comprehensive testing and benchmarking platform
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
install    : |
    DESTDIR=${installdir} bash ./install-sh %PREFIX%
