name       : phoronix-test-suite
version    : 10.2.2
release    : 25
source     :
    - https://github.com/phoronix-test-suite/phoronix-test-suite/archive/v10.2.2.tar.gz : 2f214dc19bfe61cf546084798a88c7be642222e66d5523f7f8bb0ce795c66534
license    : GPL-3.0-or-later
component  : programming
homepage   : https://www.phoronix-test-suite.com/
summary    : Comprehensive testing and benchmarking platform
description: |
    The Phoronix Test Suite is a comprehensive testing and benchmarking platform. It allows for carrying out tests in a fully automated manner from test installation to execution and reporting. All tests are meant to be easily reproducible, easy-to-use, and support fully automated execution.
builddeps  :
    - xdg-utils
rundeps    :
    - php
setup      : |
    %patch -p1 < $pkgfiles/0001-Re-enable-systemd-inhibit.patch
    %patch -p1 < $pkgfiles/0002-Enable-stateless-bash_completion.patch
install    : |
    DESTDIR="$installdir" bash ./install-sh %PREFIX%
